# 参考: https://github.com/Zenithar/zenithar.hugo/blob/master/config.toml
baseurl = "https://kwmt27.net/"
languageCode = "ja"
title = "Androg"
theme = "hugo-theme-crisp"


[params]
  DateForm = "Jan 02 , 2006"
  languageCode = "ja"
  countryCode = "ja"

  # Warning Keys are case sensitives
#  Subtitle = "Il existe moins bien mais c'est plus cher !"
#  description = "Dévéloppeur, bloggeur enthousiaste, curieux de toutes nouvelles technologies liées à la sécurité, l'architecture, et le web."
#  cover = "/images/cover.jpg"

  # Google analytics
  ga = "UA-39334884-1"
  twitter = "kwmt27"
  github = "kwmt"
  disqus = "kwmt27"

[indexes]
  category = "categories"
  tag = "tags"

[permalinks]
  post = "/:year/:month/:day/:filename/"
